plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	maven {
		name = 'TerraformersMC'
		url = 'https://maven.terraformersmc.com/releases/'
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	implementation "com.terraformersmc:modmenu:${project.modmenu_version}"
}

sourceSets {
	main {
		java {
			exclude "restudio/reglass/client/screen/world/**"
			exclude "restudio/reglass/client/screen/widget/world/**"
			exclude "restudio/reglass/client/gui/LiquidGlassGuiElementRenderer.java"
			exclude "restudio/reglass/mixin/accessor/GuiRendererAccessor.java"
			exclude "restudio/reglass/mixin/accessor/TextIconButtonWidgetAccessor.java"
			exclude "restudio/reglass/mixin/client/GuiRendererMixin.java"
			exclude "restudio/reglass/mixin/client/MinecraftClientMixin.java"
			exclude "restudio/reglass/mixin/widgets/TooltipStateMixin.java"
		}
	}
}

processResources {
	def properties = [
			version: project.version,
			loader_dependency: project.loader_dependency,
			minecraft_dependency: project.minecraft_dependency,
			java_dependency: project.java_dependency,
			fabric_api_dependency: project.fabric_api_dependency
	]

	inputs.properties properties

	filesMatching("fabric.mod.json") {
		expand properties
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = project.java_version.toInteger()
}

java {
	withSourcesJar()

	toolchain {
		languageVersion = JavaLanguageVersion.of(project.java_version.toInteger())
	}

	sourceCompatibility = JavaVersion.toVersion(project.java_version)
	targetCompatibility = JavaVersion.toVersion(project.java_version)
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}
}
